services: 
  pipeline:
    build: 
      context: .
      dockerfile: ingestion/Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
    container_name: pipeline
    command: ["python", "main.py"]
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres-db:5432/vuln_intel_db
    volumes:
      - ./ingestion/:/app/ingestion
      - ./services/:/app/services
      - ./scoring/:/app/scoring
      - ./prioritization/:/app/prioritization
      - ./database/:/app/database
      - ./data/:/app/data
      - ./main.py:/app/main.py

  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vuln_intel_db
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data: {}
    