"""
This module provides a client for interacting with a Large Language Model (LLM) via the OpenRouter API.
The LLMClient class encapsulates the functionality to send prompts to the LLM and receive structured
responses based on a specified JSON schema. The client uses the OpenAI SDK to communicate with the OpenRouter API.
The API key for authentication is expected to be set in the environment variable OPENROUTER_KEY.
"""

import os
from openai import OpenAI
from dotenv import load_dotenv

from .schemas import *

load_dotenv()

class LLMClient:
	""" A client for interacting with a Large Language Model (LLM) via the OpenRouter API. 
	This class provides methods to generate responses from the LLM based on prompts. The API key for authentication is expected to
	be set in the environment variable OPENROUTER_KEY. The default model used for generating responses can be specified during initialization.	

	Attributes:
		api_key (str): The API key for authenticating with the OpenRouter API.
		model_name (str): The name of the LLM model to use for generating responses.

	"""

	def __init__(self, model:str = "google/gemini-3.1-flash-lite"):
		""" Initialize the LLMClient with the specified model. The API key is retrieved from the environment variable OPENROUTER_KEY. 

		Args:
			model (str): The model to use for generating responses. Defaults to "google/gemini-3.1-flash-lite".

		Raises:
			ValueError: If the OPENROUTER_KEY environment variable is not set.
		"""
		self.api_key = os.getenv("OPENROUTER_KEY")
		if not self.api_key:
			raise ValueError("OPENROUTER_KEY is not set.")
		
		self.model_name = model

		# Initialize the OpenAI SDK client pointing to OpenRouter's endpoint
		self.client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=self.api_key,
        )

	def generate_response(self, instruction: str,prompt: str, response_format: dict = None) -> dict | None:
		""" Generate a structured response from the LLM based on the provided prompt and JSON schema.

		Args:
            prompt (str): The user prompt to send to the LLM for generating a response.
            response_format (dict): The JSON schema definition dictionary for the structured output.

        Returns:
            dict | None: The parsed response generated by the LLM, or None if the request failed.
		"""
		try:
			response = self.client.chat.completions.parse(
				model = self.model_name,
				messages=[
					{"role": "system", "content": instruction},
					{"role": "user", "content": prompt},
				],
				response_format = response_format
			)
			return response.choices[0].message.parsed
	
		except Exception as e:
				# Extract raw text from OpenAI SDK exception if available
				raw_text = getattr(getattr(e, "response", None), "choices", [None])[0]
				raw_text = getattr(getattr(raw_text, "message", None), "content", None)

		# Fallback cleanup when automatic SDK parsing failed
		try:
			cleaned = self.clean_json_string(raw_text or "")
			return response_format.model_validate_json(cleaned)
		except Exception as err:
			print(f"[-] Parsing failed: {err}\nRaw text: {raw_text}")
			return None
				

	def clean_json_string(raw_text: str) -> str:
		"""Removes markdown code fences if the LLM accidentally included them."""
		cleaned = raw_text.strip()
		if cleaned.startswith("```json"):
			cleaned = cleaned[7:]  # Strip off the opening ```json
		if cleaned.startswith("```"):
			cleaned = cleaned[3:]  # Strip off opening ``` if no language tag
		if cleaned.endswith("```"):
			cleaned = cleaned[:-3] # Strip off closing ```
		return cleaned.strip()
